apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx-hpa-dep
  namespace: learn

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngx-hpa-dep

  template:
    metadata:
      labels:
        app: ngx-hpa-dep
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80

        # 一定要用 resources 字段写清楚资源配额，否则 HorizontalPodAutoscaler 
        # 会无法获取 Pod 的指标，也就无法实现自动化扩缩容。
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 100m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ngx-hpa-svc
  namespace: learn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ngx-hpa-dep