apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis-sts
  name: redis-sts
  namespace: learn
spec:
  serviceName: redis-svc
  replicas: 2
  selector:
    matchLabels:
      app: redis-sts
  template:
    metadata:
      labels:
        app: redis-sts
    spec:
      containers:
      - image: redis:5-alpine
        name: redis
        ports: 
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: learn

spec:
  # Pod 已经有了稳定的域名，外界访问服务就不应该再通过 Service 这一层了
  # 所以，从安全和节约系统资源的角度考虑，k8s 不需要为这个 svc 分配 IP
  clusterIP: None
  selector:
    app: redis-sts

  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379