
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-5m-pvc
  namespace: learn

spec:
  # 直接使用默认的 sc 类型创建 sc 实例
  storageClassName: host-test
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi