
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-10m-pv

spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Mi

  nfs:
    path: /tmp/nfs/10m-pv
    server: 172.16.194.134