
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-static-pvc
  namespace: learn

spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany

  resources:
    requests:
      storage: 10Mi