# 用来查询 coredns
# 例子：查询 kube-dns 本身
# kubectl exec busybox -- nslookup kube-dns.kube-system
# Server:    x.x.x.x
# Address 1: x.x.x.x kube-dns.kube-system.svc.cluster.local

# Name:      kube-dns.kube-system
# Address 1: x.x.x.x kube-dns.kube-system.svc.cluster.local

apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - name: busybox
    image: gcr.io/google_containers/busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
