apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  #sessionAffinity: ClientIP
  #sessionAffinityConfig:
  #  clientIP:
  #    timeoutSeconds: 10800
  sessionAffinity: None
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: web
  selector:
    app: webapp
