#在默认情况下，Node的kube-proxy会在全部网卡（0.0.0.0）上绑定
#NodePort端口号。
#在很多数据中心环境中，一台主机会配置多块网卡，作用各不相
#同（例如存在业务网卡和管理网卡等）。从Kubernetes 1.10版本开
#始，kube-proxy可以通过设置特定的IP地址将NodePort绑定到特定的网
#卡上，而无须绑定在全部网卡上，其设置方式为配置启动参数“--
#nodeport-addresses”，指定需要绑定的网卡IP地址，多个地址之间使用
#逗号分隔。例如仅在10.0.0.0 和 x.x.x.x 对应的网卡上绑定NodePort
#端口号，对其他IP地址对应的网卡不会进行绑定，配置如下：
# --nodeport-addresses=10.0.0.0/8,x.x.x.x/24

apiVersion: v1
kind: Service
metadata:
  name: webapp-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32080
  selector:
    app: webapp

# eks get svc
# NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
# webapp-nodeport         NodePort    x.x.x.x          <none>        80:32080/TCP   12m

# 端口解释：
# port：ClusterIP 的端口
# nodePort：NodePort 的端口
# targetPort：endpoint 的端口