
apiVersion: v1
kind: Pod
metadata:
  name: ngx-pod-probe
  namespace: learn

spec:
  volumes:
  - name: ngx-conf-vol
    configMap:
      name: ngx-conf-probe

  containers:
  - image: nginx:alpine
    name: ngx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /etc/nginx/conf.d
      name: ngx-conf-vol

    startupProbe:
      periodSeconds: 1
      exec:
        command: ["cat", "/var/run/nginx.pid"]

    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      tcpSocket:
        port: 80

    readinessProbe:
      periodSeconds: 5
      httpGet:
        path: /ready
        port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ngx-conf-probe
  namespace: learn

data:
  default.conf: |
    server {
      listen 80;
      location = /ready {
        return 200 'I am ready';
      }
      location =/ {
        return 200 'nginx';
      }
    }